/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ProductsImport } from './routes/products'
import { Route as ProductsProductIdImport } from './routes/products.$productId'
import { Route as CartImport } from './routes/cart'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const ProductsLazyImport = createFileRoute('/products')()
const CartLazyImport = createFileRoute('/cart')()
const ProductsProductIdLazyImport = createFileRoute('/products/$productId')()

// Create/Update Routes

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
})

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
})

const ProductsRoute = ProductsImport.update({
  path: '/products',
  getParentRoute: () => rootRoute,
})

const CartRoute = CartImport.update({
  path: '/cart',
  getParentRoute: () => rootRoute,
})

const ProductsProductIdRoute = ProductsProductIdImport.update({
  path: '/products/$productId',
  getParentRoute: () => rootRoute,
})

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/products': {
      preLoaderRoute: typeof ProductsImport
      parentRoute: typeof rootRoute
    }
    '/cart': {
      preLoaderRoute: typeof CartImport
      parentRoute: typeof rootRoute
    }
    '/products/$productId': {
      preLoaderRoute: typeof ProductsProductIdImport
      parentRoute: typeof rootRoute
    }
  }
}

import { Route as AdminImport } from './routes/admin'
import { Route as AdminDashboardImport } from './routes/admin.dashboard'
import { Route as AdminCustomersImport } from './routes/admin.customers'

const AdminRoute = AdminImport.update({
  path: '/admin',
  getParentRoute: () => rootRoute,
})

const AdminDashboardRoute = AdminDashboardImport.update({
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
})

const AdminCustomersRoute = AdminCustomersImport.update({
  path: '/admin/customers',
  getParentRoute: () => AdminRoute,
})

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/admin/customers': {
      preLoaderRoute: typeof AdminCustomersImport
      parentRoute: typeof AdminImport
    }
    '/admin/dashboard': {
      preLoaderRoute: typeof AdminDashboardImport
      parentRoute: typeof AdminImport
    }
  }
}

import { Route as AdminProductsImport } from './routes/admin.products'

const AdminProductsRoute = AdminProductsImport.update({
  path: '/admin/products',
  getParentRoute: () => AdminRoute,
})

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin/products': {
      preLoaderRoute: typeof AdminProductsImport
      parentRoute: typeof AdminImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutRoute,
  ProductsRoute,
  CartRoute,
  ProductsProductIdRoute,
  AdminRoute.addChildren([AdminDashboardRoute, AdminCustomersRoute, AdminProductsRoute]),
])

/* prettier-ignore-end */
